### ISSUE TITLE
Referenced assembly 'Fissoft.EntityFramework.Fts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

### ISSUE THREAD

**Issue by icnocop** [fissoft/Fissoft.EntityFramework.Fts#2]
Thank you for Fissoft.EntityFramework.Fts 1.0.0.8.

When I try to reference Fissoft.EntityFramework.Fts.dll in a strong named assembly, I get the following error:
`Referenced assembly 'Fissoft.EntityFramework.Fts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

I expected the assembly to be signed by a strong name so that it can be used by other strong-named assemblies.

Thank you!

**Comment by chsword** [comment]
thanks ,I'v add a  strong name already.

**Comment by chsword** [comment]
#
