### ISSUE TITLE
return null use library fts

### ISSUE THREAD

**Issue by pramirhossein** [fissoft/Fissoft.EntityFramework.Fts#7]
return null on use code : 
`            var text = FullTextSearchModelUtil.Contains("web", true);
            var query = db.Mainindustapp.Where(c => c.UnitName.Contains(text)).ToList();
            return query.ToList();`

return data on use code :

`    Mainindustapp = db.database.SqlQuery
      ("SELECT * FROM[DB_table].[dbo].[Mainindustapps] WHERE FREETEXT(([UnitName], [Product]), @p0)", SearchString);`

**Comment by chsword** [comment]
```
var query = db.Mainindustapp.Where(c => c.UnitName.Contains(text)).ToList(); 
```
will return 
``` sql
SELECT 
    * --。。。
    FROM [dbo].[Mainindustapp] AS [Extent1]
    WHERE CONTAINS([Extent1].[UnitName], @p__linq__0); -- p__linq__0: '(web)'
```

**Comment by chsword** [comment]
You can use this feature 

#10 

And try the code:
``` C#

var text = FullTextSearchModelUtil.FreeText("web", true); 
var query = db.Mainindustapp.Where(c => (c.UnitName+c.Product).Contains(text)).ToList(); 

```
